#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT_DIR="${1:-.agent-work/11_ARCHIVE/visual-workspace-evidence/manual-$(date +%Y%m%d%H%M%S)}"
MANIFEST="$OUT_DIR/workspace-native-screenshot-manifest.json"
mkdir -p "$OUT_DIR"

CURRENT_JOB="unknown"
if [[ -f .agent-work/07_JOBS/CURRENT.md ]]; then
  CURRENT_JOB="$(python3 - <<'PY'
from pathlib import Path
import re
text = Path('.agent-work/07_JOBS/CURRENT.md').read_text(encoding='utf-8', errors='ignore')
match = re.search(r'(JOB-[0-9]+)', text)
print(match.group(1) if match else 'unknown')
PY
)"
fi

python3 - "$MANIFEST" "$CURRENT_JOB" <<'PY'
import json, sys, datetime, os
manifest_path, job_id = sys.argv[1:3]
required = [
  "live-normal", "missing-reports", "blocker-present", "final-ready",
  "dense-20", "dense-50-search-filter", "stale-last-good", "demo-fallback",
  "error-state", "keyboard-focus", "reduced-motion", "read-only-security",
]
manifest = {
  "schema": "workspace-native-screenshot-manifest.v1",
  "source": "native-tauri-required",
  "releaseProof": False,
  "generatedAt": datetime.datetime.now(datetime.timezone.utc).isoformat(),
  "jobId": job_id,
  "outputDirectory": os.path.dirname(manifest_path),
  "appRuntime": os.environ.get("AGENTDOCK_NATIVE_APP_RUNTIME", "unverified"),
  "captureCommand": os.environ.get("AGENTDOCK_NATIVE_SCREENSHOT_CMD", ""),
  "importDirectory": os.environ.get("AGENTDOCK_NATIVE_SCREENSHOT_IMPORT_DIR", ""),
  "notes": [
    "Current-job manifest generated by the reference UI evidence harness.",
    "releaseProof remains false unless every required state has a real PNG path from native Tauri runtime.",
    "Browser/static export screenshots must not be counted as native release proof.",
    "Set AGENTDOCK_NATIVE_SCREENSHOT_IMPORT_DIR to a directory containing <state>.png files, or set AGENTDOCK_NATIVE_SCREENSHOT_CMD with {id} and {path} placeholders to capture real native screenshots."
  ],
  "requiredStates": [
    {"id": state, "source": "native-tauri", "path": None, "status": "missing", "notes": "not captured"}
    for state in required
  ]
}
with open(manifest_path, 'w', encoding='utf-8') as f:
    json.dump(manifest, f, indent=2, ensure_ascii=False)
    f.write('\n')
PY

if [[ -n "${AGENTDOCK_NATIVE_SCREENSHOT_IMPORT_DIR:-}" ]]; then
  for src in "$AGENTDOCK_NATIVE_SCREENSHOT_IMPORT_DIR"/*.png; do
    [[ -f "$src" ]] || continue
    dest="$OUT_DIR/$(basename "$src")"
    if [[ "$(realpath "$src")" != "$(realpath -m "$dest")" ]]; then
      cp "$src" "$dest"
    fi
  done
fi

if [[ -n "${AGENTDOCK_NATIVE_SCREENSHOT_CMD:-}" ]]; then
  python3 - "$OUT_DIR" <<'PY'
import os, shlex, subprocess, sys
from pathlib import Path
out = Path(sys.argv[1])
required = [
  "live-normal", "missing-reports", "blocker-present", "final-ready",
  "dense-20", "dense-50-search-filter", "stale-last-good", "demo-fallback",
  "error-state", "keyboard-focus", "reduced-motion", "read-only-security",
]
cmd_template = os.environ["AGENTDOCK_NATIVE_SCREENSHOT_CMD"]
for state in required:
    path = out / f"{state}.png"
    cmd = cmd_template.format(id=shlex.quote(state), path=shlex.quote(str(path)))
    subprocess.run(cmd, shell=True, check=False, timeout=30)
PY
fi

python3 - "$MANIFEST" "$OUT_DIR" <<'PY'
import json, os, sys
from pathlib import Path
manifest_path = Path(sys.argv[1])
out_dir = Path(sys.argv[2])
manifest = json.loads(manifest_path.read_text(encoding='utf-8'))
all_captured = True

def is_png(path: Path) -> bool:
    try:
        return path.read_bytes()[:8] == b"\x89PNG\r\n\x1a\n"
    except OSError:
        return False

def has_visual_content(path: Path) -> bool:
    try:
        from PIL import Image
        image = Image.open(path).convert("RGB")
        width, height = image.size
        if width < 640 or height < 400:
            return False
        step_x = max(1, width // 40)
        step_y = max(1, height // 30)
        samples = []
        for y in range(0, height, step_y):
            for x in range(0, width, step_x):
                samples.append(image.getpixel((x, y)))
        unique = len(set(samples))
        avg = sum(sum(pixel) for pixel in samples) / (len(samples) * 3)
        return unique >= 8 and avg >= 8
    except Exception:
        return True

for state in manifest["requiredStates"]:
    state_id = state["id"]
    candidate = out_dir / f"{state_id}.png"
    if candidate.exists() and candidate.stat().st_size > 0 and is_png(candidate) and has_visual_content(candidate):
        state["path"] = str(candidate)
        state["status"] = "captured"
        state["notes"] = "PNG file present and non-blank; QA must confirm it is from native Tauri runtime."
    elif candidate.exists() and candidate.stat().st_size > 0 and is_png(candidate):
        all_captured = False
        state["path"] = str(candidate)
        state["status"] = "invalid"
        state["notes"] = "PNG exists but appears blank/low-information; not accepted as native release evidence"
    else:
        all_captured = False
        state["path"] = None
        state["status"] = "missing"
        state["notes"] = "missing real native PNG capture"
manifest["releaseProof"] = bool(all_captured and os.environ.get("AGENTDOCK_NATIVE_RUNTIME_CONFIRMED") == "1")
if all_captured and not manifest["releaseProof"]:
    manifest["notes"].append("All PNG paths exist, but releaseProof remains false until AGENTDOCK_NATIVE_RUNTIME_CONFIRMED=1 and QA verifies native Tauri origin.")
manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding='utf-8')
missing = [s['id'] for s in manifest['requiredStates'] if s['status'] != 'captured']
print(f"workspace native screenshot harness wrote manifest {manifest_path}")
print(f"captured={len(manifest['requiredStates'])-len(missing)}/{len(manifest['requiredStates'])} releaseProof={manifest['releaseProof']}")
if missing:
    print("missing=" + ",".join(missing))

if os.environ.get("AGENTDOCK_REQUIRE_RELEASE_PROOF") == "1":
    errors = []
    if not manifest.get("releaseProof"):
        errors.append("releaseProof is not true")
    if len(manifest.get("requiredStates", [])) != 12:
        errors.append(f"requiredStates count is {len(manifest.get('requiredStates', []))}, expected 12")
    for state in manifest.get("requiredStates", []):
        state_id = state.get("id", "unknown")
        state_path = state.get("path")
        if state.get("status") != "captured":
            errors.append(f"{state_id} status is {state.get('status')}, expected captured")
        if not state_path:
            errors.append(f"{state_id} path is missing")
            continue
        path = Path(state_path)
        if not path.exists():
            errors.append(f"{state_id} path does not exist: {state_path}")
        elif not is_png(path):
            errors.append(f"{state_id} path is not a PNG: {state_path}")
    if errors:
        print("release proof assertion failed:")
        for error in errors:
            print(f"- {error}")
        raise SystemExit(4)
    print("release proof assertion ok")
PY
